name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      -  name: Install dependencies
         run: npm install
      - name: Build
        run: npm run build
      
      - name: Deploy
        run: | 
          npx angular-cli-ghpages --dir=dist/msr-collection
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.